version: '2'
services:
    kbloft-app:
        image: kbloft
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@kbloft-oracle:1521:kbloft
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
